git checlanguage: generic

stages:
  - name: self-test
    if: type = push
  - name: flutter
    if: branch = master OR type = pull_request
  - name: native
    if: branch = master OR type = pull_request

_flutter_job_template: &_flutter_job_template
  before_script:
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  script:
    - flutter packages get
    - flutter test

_android_job_template: &android_job_template
  language: android
  android:
    components:
      - tools
      - android-28
      - android-29
      - build-tools-28.0.3
      - build-tools-29.0.5
      - extra-android-m2repository
  env:
    global:
      - GRADLE_OPTS="-Xms128m"
      - ABI="default;armeabi-v7a"
  before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  cache:
    directories:
      - $HOME/.m2
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
  before_script:
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  script:
    - cd example
    - flutter build apk

_ios_job_template: &ios_job_template
  language: objective-c
  os: osx
  osx_image: xcode11.6
  xcode_workspave: example/ios/Runner.xcworkspace
  xcode_scheme: Runner
  before_script:
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  script:
    - cd example
    - flutter build ios --no-codesign

matrix:
  include:
    - <<: *android_job_template
      name: Build Android
      stage: native
    - <<: *ios_job_template
      name: Build iOS
      stage: native
    - <<: *_flutter_job_template
      name: Build Flutter
      stage: flutter
