language: generic
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
script:
  - flutter packages get
  - flutter test